/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as dhaCrowdsaleSol from "./DHACrowdsale.sol";
export type { dhaCrowdsaleSol };
import type * as dhaCrowndsaleSol from "./DHACrowndsale.sol";
export type { dhaCrowndsaleSol };
export type { DHAToken } from "./DHAToken";
export type { T1 } from "./T1";
